const fs = require('fs');
const path = require('path');

const HISTORY_FILE = path.join(__dirname, '../out/trust_trend.csv');
const REPORT_FILE = path.join(__dirname, '../out/stealth_attack_analysis.md');

if (!fs.existsSync(HISTORY_FILE)) {
    console.error(`History file not found: ${HISTORY_FILE}`);
    process.exit(1);
}

const data = fs.readFileSync(HISTORY_FILE, 'utf8').trim().split('\n');
const parsed = [];
for(let i=1; i<data.length; i++) {
    const row = data[i].split(',');
    if (row.length < 5) continue;
    parsed.push({
        loop: parseInt(row[0]),
        address: row[1],
        group: row[2],
        trust: parseInt(row[3]),
        isBlacklisted: row[4] === 'true'
    });
}

// Analysis Points
const ATTACK_START = 110;
const DEFENSE_TRIGGER = 115;
const END_LOOP = Math.max(...parsed.map(p => p.loop));

function getGroupStats(loop) {
    const groups = ['Honest', 'Whitewash', 'Collusion'];
    const stats = {};
    groups.forEach(g => {
        const nodes = parsed.filter(p => p.group === g && p.loop === loop);
        if (nodes.length === 0) {
            stats[g] = { avg: 0, count: 0, blacklisted: 0 };
        } else {
            const avg = nodes.reduce((a, b) => a + b.trust, 0) / nodes.length;
            const blacklisted = nodes.filter(n => n.isBlacklisted).length;
            stats[g] = { avg: avg.toFixed(2), count: nodes.length, blacklisted };
        }
    });
    return stats;
}

const preAttack = getGroupStats(ATTACK_START - 1);
const midAttack = getGroupStats(DEFENSE_TRIGGER - 1);
const postDefense = getGroupStats(DEFENSE_TRIGGER + 1);
const finalState = getGroupStats(END_LOOP);

const report = `# Stealth Attack & Defense Analysis

## Experiment Overview
- **Attack Type:** Stealth Whitewash (Low-frequency interaction + Clique formation)
- **Attack Start:** Loop ${ATTACK_START}
- **AI Defense Trigger:** Loop ${DEFENSE_TRIGGER}
- **Total Loops:** ${END_LOOP}

## Key Metrics

### 1. Pre-Attack Baseline (Loop ${ATTACK_START - 1})
| Group | Avg Trust | Node Count | Blacklisted |
|-------|-----------|------------|-------------|
| Honest | ${preAttack.Honest.avg} | ${preAttack.Honest.count} | ${preAttack.Honest.blacklisted} |
| Whitewash | ${preAttack.Whitewash.avg} | ${preAttack.Whitewash.count} | ${preAttack.Whitewash.blacklisted} |

### 2. Attack Phase (Loop ${DEFENSE_TRIGGER - 1})
*Whitewash nodes attempted to rebuild trust silently.*
| Group | Avg Trust | Delta (vs Pre) |
|-------|-----------|----------------|
| Whitewash | ${midAttack.Whitewash.avg} | ${ (midAttack.Whitewash.avg - preAttack.Whitewash.avg).toFixed(2) } |

### 3. Post-Defense Impact (Loop ${DEFENSE_TRIGGER + 1})
*AI Agent intervened to penalize suspicious cliques.*
| Group | Avg Trust | Blacklisted Count |
|-------|-----------|-------------------|
| Whitewash | ${postDefense.Whitewash.avg} | ${postDefense.Whitewash.blacklisted} / ${postDefense.Whitewash.count} |

### 4. Final State (Loop ${END_LOOP})
| Group | Avg Trust | Blacklisted Count |
|-------|-----------|-------------------|
| Honest | ${finalState.Honest.avg} | ${finalState.Honest.blacklisted} |
| Whitewash | ${finalState.Whitewash.avg} | ${finalState.Whitewash.blacklisted} |

## Conclusion
The AI Agent successfully identified the stealthy behavior pattern (rapid trust growth via clique recommendations). 
- **Detection Rate:** ${ ((finalState.Whitewash.blacklisted / finalState.Whitewash.count) * 100).toFixed(1) }% of Whitewash nodes penalized.
- **Trust Suppression:** Trust dropped from peak ${midAttack.Whitewash.avg} to ${finalState.Whitewash.avg}.

_Generated by scripts/analyze_whitewash.js_
`;

fs.writeFileSync(REPORT_FILE, report);
console.log(`Analysis saved to: ${REPORT_FILE}`);
console.log(report);
